# Generated by Django 2.2 on 2021-04-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=64)),
                ('money', models.IntegerField(verbose_name='金额')),
                ('address', models.CharField(max_length=128, verbose_name='家庭地址')),
                ('relation', models.CharField(max_length=128, verbose_name='关系')),
                ('phone', models.CharField(max_length=128, verbose_name='电话号码')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
