# Generated by Django 2.2 on 2021-04-28 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='money',
            field=models.IntegerField(null=True, verbose_name='金额'),
        ),
    ]
