# Generated by Django 2.2 on 2021-04-28 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20210428_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='address',
            field=models.CharField(max_length=128, null=True, verbose_name='家庭地址'),
        ),
        migrations.AlterField(
            model_name='book',
            name='phone',
            field=models.CharField(max_length=128, null=True, verbose_name='电话号码'),
        ),
        migrations.AlterField(
            model_name='book',
            name='relation',
            field=models.CharField(max_length=128, null=True, verbose_name='关系'),
        ),
    ]
